from .bolzano.main import calc_func
from .eliminacao_gauss.main import gauss_elimination
from .extrapolacao.main import extrapolar
from .gauss_jacobi.main import gauss_jacobi
from .gauss_seidel.main import gauss_seidel
from .interpolador_newton.main import inter_newton
from .interpolador_newton_inv.main import inter_newton_inv
from .lagrange.main import lagrange
from .metodo_bisseccao.main import bissection
from .newton_raphson.main import newton_raphson
from .secante.main import secante
from .trap_comp.main import newton_colis